### ISSUE TITLE
Round Off the decimal to 2 places in buyValue of a stock

### ISSUE THREAD

**Issue by Jigar3** [Jigar3/Wall-Street#1]
When we fetch the data of the stock from the API, we get a JSON back which contains the latestPrice of the stock, sometimes the value has 3 decimal places. We want that wherever we use the latestPrice, it should be only 2 decimals to maintain homogeniety throughout the application.
![image](https://user-images.githubusercontent.com/32068121/51025859-1c525d80-15b3-11e9-8e97-49f4f7d79d85.png)

**Comment by shivam0211** [comment]
Can I work on this?

**Comment by Jigar3** [comment]
@shivam0211 Go ahead

**Comment by vishnuk7** [comment]
@Jigar3  Can I work on this?

**Comment by Jigar3** [comment]
@shivam0211 Are you still working on this?

**Comment by shivam0211** [comment]
Yes

**Comment by prijeshb** [comment]
@Jigar3 can shares sold in fraction ??

**Comment by Jigar3** [comment]
No it can not be sold in fractions

**Comment by prijeshb** [comment]
should add validation for that !!
