### ISSUE TITLE
Create a mock up for the landing page

### ISSUE THREAD

**Issue by Jigar3** [Jigar3/Wall-Street#17]
Currently the landing page consists of a simple form for login. It would be nice if someone could design a landing page. Use [Figma](https://www.figma.com/) or maybe Adobe XD or any software you are comfortable with. 
Example: https://www.figma.com/proto/UbBMCosh41Zy4KIXVxP64VmU/Blog?node-id=0%3A1&scaling=min-zoom
I know its very bad, but was my first time. You don't need to code, just create a prototype using figma or adobe XD and share the link.

![landing](https://user-images.githubusercontent.com/32068121/51440839-23831500-1cf1-11e9-9987-b1ae14173b54.jpg)

**Comment by vishnuk7** [comment]
@Jigar3 I Completed this issue
https://www.figma.com/file/Gl1MRqYE1kWguqPmoGomIHs9/Wall-Street?node-id=0%3A1

**Comment by Jigar3** [comment]
@vishnuk7 Good Job. Really Impressed

**Comment by vishnuk7** [comment]
@Jigar3 Thanks

**Comment by anupm12** [comment]
@Jigar3 Done
https://www.figma.com/file/CIz0wfJWZR4vkGaYa3IO4Z83/Login-page?node-id=0%3A1

**Comment by Archies11** [comment]
@Jigar3 Done :+1:

Link: https://www.figma.com/file/FYLXPYH1Z5jheJtVk4iLmGIT/Untitled?node-id=0%3A1

**Comment by LalitSharma7** [comment]
@Jigar3 Done
Live link :- https://www.figma.com/file/MD5QmXbZDg89zIIQPmocGw1b/login?node-id=2%3A2


Here is the screenshot for the same
![screenshot 121](https://user-images.githubusercontent.com/38866385/52644633-33170780-2f05-11e9-9ad0-0541c283790f.png)
