### ISSUE TITLE
Make a Hero Section on the Leaderboard Page

### ISSUE THREAD

**Issue by Jigar3** [Jigar3/Wall-Street#2]
As you can see on the home page, that we have a Hero Section for the portfolio(the banner is known as the hero image). So, we want something similar to this on the Leaderboard page as well

**Comment by Archies11** [comment]
May I work on this?

**Comment by Jigar3** [comment]
@Archies11 Go ahead.

**Comment by Archies11** [comment]
I am not able to figure out which banner it is that we are referring to as the hero image? Is it the avatar of the account holder?

**Comment by Jigar3** [comment]
![image](https://user-images.githubusercontent.com/32068121/51188241-906a6980-1903-11e9-9b4c-40e56ebc2647.png)

This is the hero image. Make a same one for the leaderboard page

**Comment by Archies11** [comment]
I tried to locate the code for this banner as well as the location of this image but couldnt find it. Please help me with the same.

**Comment by Jigar3** [comment]
See line 76 in Home.tsx
