### ISSUE TITLE
Set up this project on your local machine

### ISSUE THREAD

**Issue by Jigar3** [Jigar3/Wall-Street#3]
Share a screenshot/GIF here. 10 points each for the frontend as well as backend setup

**Comment by Archies11** [comment]
I tried to clone the repo on git hub desktop but didnt work out..does setup mean downloading the node and following the steps given in the readme?

**Comment by Jigar3** [comment]
@Archies11  Setting up this project implies downloading all the stuff mentioned in README and run the project on your local machine. The application should look similar to the one in the deployed version. https://wall-street.netlify.com This is the deployed application

**Comment by tushparte** [comment]
backend is running - https://imgur.com/a/gs5tKtj

**Comment by bettercalln1ck** [comment]
![screenshot from 2019-01-22 16-22-24](https://user-images.githubusercontent.com/40137469/51530972-29e4ce80-1e62-11e9-8761-9536b6a3cbab.png)
![screenshot from 2019-01-22 16-22-21](https://user-images.githubusercontent.com/40137469/51530974-2b15fb80-1e62-11e9-8636-f242071ff076.png)
sir, backend is running but i am not able to get past sign up screen.

**Comment by Jigar3** [comment]
just go into models/user.js and replace process.env.SALT with some random string (ex. 'Hello')

**Comment by vishnuk7** [comment]
Done
![vid_gif-1549816359](https://user-images.githubusercontent.com/31013847/52536920-a34b4f00-2d86-11e9-8c93-343c6710990e.gif)

**Comment by LalitSharma7** [comment]
![img-20190212-wa0039](https://user-images.githubusercontent.com/38866385/52650415-3c59a180-2f10-11e9-9bae-d3b2e5be52ed.jpg)
![img-20190212-wa0038](https://user-images.githubusercontent.com/38866385/52650416-3c59a180-2f10-11e9-8935-93b2c92711f2.jpg)

Frontend running
