### ISSUE TITLE
Update the README file to add more details

### ISSUE THREAD

**Issue by Jigar3** [Jigar3/Wall-Street#4]

**Comment by LalitSharma7** [comment]
What kind of details sir??

**Comment by Jigar3** [comment]
Just expand onto what this projects helps with. The basic idea that you get $ 10,000 at the start and you can use them to build your portfolio. Maybe add a screenshot of gif of some of the screens will be good

**Comment by LalitSharma7** [comment]
okay

**Comment by Archies11** [comment]
Can i work on this?

**Comment by Jigar3** [comment]
@Archies11  Go ahead

**Comment by Archies11** [comment]
Sir can you please elaborate a bit on on what this project intends to do? @Jigar3

**Comment by Jigar3** [comment]
@Archies11  It is not necessary to address us as sir or ma'am while working alongside on a project. We both are contributors to the same project, there is no hierarchy here. 

Stock Markets are considered to be a risky investment, but in reality they are not. Its just a myth that investing in stock market is like gambling. This project helps people to get accustomed to buying and selling of stocks and making them feel comfortable in investing. Its helpful if you start out with virtual money and track your progress. You can build your own portfolio of stocks, monitor them for a period of time and learn about stock markets.

**Comment by Archies11** [comment]
Okay, Thank you.
