### ISSUE TITLE
Sign Up for the application

### ISSUE THREAD

**Issue by Jigar3** [Jigar3/Wall-Street#7]
Share the screenshot and use your college email ID to signup.
https://wall-street.netlify.com/

**Comment by Rattlecode17sh** [comment]
![img_20190112_141830](https://user-images.githubusercontent.com/38866385/51071371-e88c3c00-1675-11e9-948c-4b5618921f8d.jpg)

**Comment by Archies11** [comment]
![hero-background](https://user-images.githubusercontent.com/45824817/51075819-da124480-16b6-11e9-87e8-8dea9b0234d0.jpg)

**Comment by Archies11** [comment]
![capture](https://user-images.githubusercontent.com/45824817/51075830-f8784000-16b6-11e9-94b3-3a7307b26ed3.PNG)

**Comment by shivam0211** [comment]
<img width="1440" alt="screenshot 2019-01-13 at 2 01 44 am" src="https://user-images.githubusercontent.com/40915207/51078170-5d439280-16d7-11e9-80e3-d5520624483c.png">

**Comment by Jigar3** [comment]
It would be better if you could share a screenshot in which you have atleast one stock purchased

**Comment by LalitSharma7** [comment]
![screenshot 30](https://user-images.githubusercontent.com/38866385/51082701-89d8c800-1732-11e9-97d7-0182441c850e.png)

**Comment by sourabhpruthi10** [comment]
![screenshot from 2019-01-13 17-29-48](https://user-images.githubusercontent.com/25590627/51084993-f1097300-1758-11e9-866d-5f2f2108ffe3.png)

**Comment by tushparte** [comment]
<img width="1435" alt="screenshot 2019-01-14 at 1 58 32 pm" src="https://user-images.githubusercontent.com/43264385/51102349-9b8aa000-1804-11e9-8786-0627dac442cf.png">

**Comment by pal-0123** [comment]
![screenshot from 2019-01-23 02-39-17](https://user-images.githubusercontent.com/46341065/51512821-ec664e00-1e2d-11e9-8237-b6f397ae2923.png)

**Comment by anupm12** [comment]
done
![image](https://user-images.githubusercontent.com/35293695/51867764-515ffd80-2372-11e9-9cf7-e8b9e090182d.png)

**Comment by vishnuk7** [comment]
done
![image](https://user-images.githubusercontent.com/31013847/52176084-d7959d00-27d3-11e9-943d-1579028fa1c8.png)

**Comment by thesmallstar** [comment]
done
![sign](https://user-images.githubusercontent.com/42006277/52489746-11f2a600-2be9-11e9-9011-599c8deabff7.png)
