### ISSUE TITLE
Make a field to display time on the Navbar section

### ISSUE THREAD

**Issue by Jigar3** [Jigar3/Wall-Street#8]
Besides the status of the market, it would be nice to have the current time displayed.

**Comment by prateek76** [comment]
@Jigar3 i want to work on this but i need help to setup it :)

`deflorator@deflorator-Aspire-E5-572G:~/Wall-Street/v2$ yarn install`
`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'`
`deflorator@deflorator-Aspire-E5-572G:~/Wall-Street/v2$ yran`
`^C`
`deflorator@deflorator-Aspire-E5-572G:~/Wall-Street/v2$ yarn`
`00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.`
`deflorator@deflorator-Aspire-E5-572G:~/Wall-Street/v2$ yarn --version`
`0.32`

i am getting error while yarn install

**Comment by Jigar3** [comment]
@prateek76 Maybe Yarn is not properly installed on your system. https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install. See this or Try running 
```
npm install
```

**Comment by prateek76** [comment]
@Jigar3  i want to work on this issue :)

**Comment by Jigar3** [comment]
@prateek76 Go ahead

**Comment by prateek76** [comment]
@Jigar3 i am out, this issue is open now

**Comment by shivam0211** [comment]
Can I work on this issue?

**Comment by Jigar3** [comment]
@shivam0211 go ahead

**Comment by vishnuk7** [comment]
@Jigar3  Can I work on this issue?
